version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ruby
#     overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: root
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root
