version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ruby
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/applicationStart.sh
      runas: ubuntu
#   ApplicationStop:
#     - location: scripts/applicationStop.sh
#       runas: root
